# Generated by Django 5.0.6 on 2024-07-18 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0012_likedrepy_reply_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="likedposts",
                through="a_posts.LikePost",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
