# Generated by Django 5.0.6 on 2024-08-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_landingpages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="access_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
